In [3]:
import torch

In [35]:
x = torch.tensor([2.5,0.1], dtype=torch.float16)

In [36]:
print(x)
print(x.size())
print(x.dtype)

tensor([2.5000, 0.1000], dtype=torch.float16)
torch.Size([2])
torch.float16


In [37]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x, '\n', y)

tensor([[0.8723, 0.8724],
        [0.3500, 0.7826]]) 
 tensor([[0.7699, 0.2099],
        [0.2095, 0.8826]])


In [43]:
#element wise addition
z = x + y
print(z)
z = torch.add(x,y)
print(z)

#inplace addition
y.add_(x) # modifies y
print(y)

#element wise subtraction
z = x - y
z = torch.sub(x,y)
print(z)

tensor([[2.5145, 1.9547],
        [0.9096, 2.4478]])
tensor([[2.5145, 1.9547],
        [0.9096, 2.4478]])
tensor([[2.5145, 1.9547],
        [0.9096, 2.4478]])
tensor([[-1.6422, -1.0823],
        [-0.5595, -1.6652]])


In [47]:
#slicing
x = torch.rand(5,3)
print(x)
print(x[:,0])
print(x[1,:])
print(x[1,1], x[1,1].item())

tensor([[0.9951, 0.8857, 0.8131],
        [0.4291, 0.4185, 0.6035],
        [0.7163, 0.8769, 0.4684],
        [0.7463, 0.2793, 0.5573],
        [0.7901, 0.7530, 0.8100]])
tensor([0.9951, 0.4291, 0.7163, 0.7463, 0.7901])
tensor([0.4291, 0.4185, 0.6035])
tensor(0.4185) 0.4185420274734497


In [57]:
#reshaping
x = torch.rand(4,4)
print(x.shape)
y = x.view(16)
print(y.shape)
y = x.view(-1, 8)
print(y.shape)

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


In [67]:
#converting to numpy
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print(b, type(b)) #note, if on CPU, both objects are in the same memory location
a.add_(1)
print(a, " | ", b)
print()

#converting from numpy
a = np.ones(5)
print(a)
b = torch.from_numpy(a) #again, both are in same memory if on CPU
print(b)
a += 1
print(a, " | ", b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])  |  [2. 2. 2. 2. 2.]

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]  |  tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [69]:
#require gradient - if needed for optimization
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)