In [26]:
import torch
import torch.nn as nn
import numpy as np

In [27]:
# softmax

# numpy
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

x = np.array([2.0, 1.0, 0.1])
outputs = softmax(x)
print(outputs)

#pytorch
x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim=0)
print(outputs)

[0.65900114 0.24243297 0.09856589]
tensor([0.6590, 0.2424, 0.0986])


In [28]:
# cross-entropy loss

# numpy
def cross_entropy(actual, predicted):
    loss = -np.sum(actual*np.log(predicted))
    return loss # / float(predicted.shape[0]) to normalize

Y = np.array([1,0,0]) # must be One Hot Encoded

y_pred_good = np.array([0.7,0.2,0.1])
y_pred_bad = np.array([0.1, 0.3, 0.6])
l1 = cross_entropy(Y, y_pred_good)
l2 = cross_entropy(Y, y_pred_bad)
print(f'{l1:.3f}, {l2:.3f}')

# pytorch
# note, nn.CrossEntropyLoss applies softmax, so no softmax last layer
# also Y has class labels, not One Hot Encoded, and y_pred has raw scores

loss = nn.CrossEntropyLoss()
Y = torch.tensor([0]) # class 0

y_pred_good = torch.tensor([[2.0, 1.0, 0.1]]) # has size n_samples x n_classes (1x3), no softmax
y_pred_bad = torch.tensor([[0.5, 2.0, 0.3]])
l1 = loss(y_pred_good, Y)
l2 = loss(y_pred_bad, Y)
print(f'{l1.item():.3f}, {l2.item():.3f}')

_, predictions1 = torch.max(y_pred_good, 1)
_, predictions2 = torch.max(y_pred_bad, 1)

print(predictions1)
print(predictions2)
print()

# 3 samples
Y = torch.tensor([2,0,1])
y_pred_good = torch.tensor([[0.01, 1.0, 2.1], [2.0, 1.0, 0.1], [0.01, 1.0, 0.1]]) # 3x3 now
y_pred_bad = torch.tensor([[0.5, 2.0, 0.3], [0.01, 1.0, 0.1], [2.0, 1.0, 0.1]])
l1 = loss(y_pred_good, Y)
l2 = loss(y_pred_bad, Y)
print(f'{l1.item():.3f}, {l2.item():.3f}')

_, predictions1 = torch.max(y_pred_good, 1)
_, predictions2 = torch.max(y_pred_bad, 1)

print(predictions1)
print(predictions2)

0.357, 2.303
0.417, 1.841
tensor([0])
tensor([1])

0.456, 1.674
tensor([2, 0, 1])
tensor([1, 1, 0])


In [32]:
# multi-class neural net

class NeuralNet2(nn.Module):
    
    def __init(self, input_size, hidden_size, num_classes):
        super(NeuralNet2, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, num_classes)
    
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        # note: no softmax layer
        return out

model = NeuralNet2(input_size=28*28, hidden_size=5, num_classes=3)
criterion = nn.CrossEntropyLoss() # applies softmax

TypeError: NeuralNet2.__init__() got an unexpected keyword argument 'input_size'

In [36]:
# binary neural net - use BCELoss

class NeuralNet2(nn.Module):
    
    def __init(self, input_size, hidden_size):
        super(NeuralNet2, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)
    
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        y_pred = torch.sigmoid(out) # sigmoid at the end
        return y_pred

model = NeuralNet2(input_size=28*28, hidden_size=5)
criterion = nn.BCELoss()

TypeError: NeuralNet2.__init__() got an unexpected keyword argument 'input_size'